# Generated by Django 4.0 on 2024-07-28 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('c_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_connect', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-c_date'],
            },
        ),
        migrations.CreateModel(
            name='CorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('post_no_or_title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('cor_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_connect', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-cor_date'],
            },
        ),
        migrations.CreateModel(
            name='DelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=250)),
                ('message', models.TextField(default='not provided')),
                ('del_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-del_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tags', models.TextField(null=True)),
                ('category', models.CharField(choices=[('Social Psychology', 'Social Psychology'), ('Psychopathology', 'Psychopathology'), ('General Psychology', 'General Psychology'), ('Authors', 'Authors'), ('Statistics', 'Statistics'), ('Research', 'Research')], max_length=100)),
                ('intro', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('img_url', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('likes', models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='save_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
