# Generated by Django 4.0 on 2024-07-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_author_delete_signeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
