# Generated by Django 4.0 on 2024-07-08 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_ccustomer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccustomer',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 18, 40, 37, 93288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 18, 40, 37, 93288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 18, 40, 37, 94287, tzinfo=utc)),
        ),
    ]
