# Generated by Django 4.0 on 2024-07-10 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_real_title_alter_ccustomer_c_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='real_title',
        ),
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.CharField(default='Not provided', max_length=250),
        ),
        migrations.AlterField(
            model_name='ccustomer',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 7, 59, 50, 575600, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 7, 59, 50, 574604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 7, 59, 50, 576604, tzinfo=utc)),
        ),
    ]
