# Generated by Django 4.0 on 2024-07-10 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_ccustomer_c_date_alter_post_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='All', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ccustomer',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 8, 26, 5, 878231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 8, 26, 5, 877259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 8, 26, 5, 878231, tzinfo=utc)),
        ),
    ]
