# Generated by Django 4.0 on 2024-07-10 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_category_post_tags_alter_ccustomer_c_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccustomer',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 8, 38, 31, 537124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Social Psychology', 'Social Psychology'), ('Psychopathology', 'Psychopathology'), ('General Psychology', 'General Psychology'), ('Authors', 'Authors'), ('Statistics', 'Statistics'), ('Research', 'Research')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 8, 38, 31, 536121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 8, 38, 31, 537124, tzinfo=utc)),
        ),
    ]
