# Generated by Django 4.0 on 2024-07-10 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_ccustomer_c_date_alter_subscriber_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccustomer',
            name='c_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date_join',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
