# Generated by Django 4.0 on 2024-07-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_ccustomer_c_date_alter_subscriber_date_join'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
    ]
