# Generated by Django 4.0 on 2024-07-10 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_coruser_alter_ccustomer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccustomer',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coruser',
            name='cor_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
