# Generated by Django 4.0 on 2024-07-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_ccustomer_c_date_alter_coruser_cor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='otp',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
