# Generated by Django 4.0 on 2024-07-11 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_subscriber_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
