# Generated by Django 4.0 on 2024-07-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_alter_subscriber_date_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='otp',
        ),
    ]
