# Generated by Django 4.0 on 2024-07-16 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_remove_subscriber_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnSubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=250)),
                ('message', models.TextField(default='not provided')),
                ('cor_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
