# Generated by Django 4.0 on 2024-07-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_unsubuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unsubuser',
            options={'ordering': ['-unsub_date']},
        ),
        migrations.RenameField(
            model_name='unsubuser',
            old_name='cor_date',
            new_name='unsub_date',
        ),
    ]
